# permissions for end users to edit agekeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agekey-editor-role
rules:
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - agekeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - agekeys/status
  verbs:
  - get
