# permissions for end users to edit agesecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agesecret-editor-role
rules:
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - agesecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - agesecrets/status
  verbs:
  - get
