# permissions for end users to view agesecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agesecret-viewer-role
rules:
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - agesecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitopssecret.snappcloud.io
  resources:
  - agesecrets/status
  verbs:
  - get
